---
title: "Scenario Analyse Leefgebieden: Bruine Korenbout"
author: "Bert Van Hecke"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: true
    toc: true
    theme: flatly
params:
  scenario_rds_path: "../Scenario_rds/TV_Scenario_bosbehoudss_ss31fix_tvg_vrij_2026.rds"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  include = FALSE
)

library(knitr)
library(here)
library(tidyverse)
library(sf)
library(terra)
library(readxl)
library(tidyterra)
library(leaflet)
library(kableExtra)
library(data.table)

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(terra::intersect)
conflicted::conflicts_prefer(terra::any)

# Exacte hectare-berekening behouden (cellSize voor 100% precisie)
calc_ha_exact <- function(r) {
  if(is.null(r)) return(0)
  if(all(is.na(terra::values(r, mat=FALSE)))) return(0)
  area_raster <- r * terra::cellSize(r, unit = "ha")
  val <- terra::global(area_raster, "sum", na.rm = TRUE)[[1]]
  return(as.numeric(val))
}
```

# Informatie ophalen
```{r Informatie}
# 1. Fail-safe voor handmatig knitten vs masterscript uitvoering
if (basename(params$scenario_rds_path) == params$scenario_rds_path) {
  scenario_path <- here(params$scenario_rds_path)
} else {
  scenario_path <- params$scenario_rds_path
}

scen_volledig <- basename(scenario_path)
scenario_naam <- gsub("^TV_Scenario_|.rds$", "", scen_volledig)

message(paste("-> Script gestart voor Scenario:", scenario_naam))

# 2. Soortkenmerken ophalen
df <- read_excel(here("data/input/Excel_files/Soorten_bwk_afstanden.xlsx"))
soort <- "bruinekorenbout"

resultaat <- df %>%
  mutate(Soort_clean = tolower(trimws(Soort))) %>% 
  filter(Soort_clean == soort) %>%
  select(Type, MinOpp_ha, AfstandBiotopen_m, Dispersiecap_m)

buffer_m <- resultaat$Dispersiecap_m[1]

rm(df, resultaat)
```

# Gebied voorbereiden (Turnhouts Vennegebied)
```{r Gebied Voorbereiden}
area_shape  <- vect(here("data/input/Turnhouts_Vennegebied.shp"))
master_grid <- rast(here("data/input/Raster_Vlaanderen/Vlaanderen_MasterGrid_10m.tif"))[[1]]

df_namen_sleutel <- read_csv(here("data/input/Excel_files/BWK_Laag_Namen_2025.csv"), show_col_types = FALSE)
gouden_namenlijst <- tolower(trimws(df_namen_sleutel$Laagnaam))

area_shape_proj <- project(area_shape, crs(master_grid))
area_buffer_fix <- buffer(area_shape_proj, width = buffer_m)

message("-> Vertaalraster voor globale/lokale cellen opbouwen...")
id_raster_TV <- crop(master_grid, area_buffer_fix, snap = "near")

buffer_masker <- terra::rasterize(area_buffer_fix, id_raster_TV, field = 1)
lokale_cellen <- terra::cells(buffer_masker)

coordinaten <- terra::xyFromCell(id_raster_TV, lokale_cellen)
studiegebied_globale_ids <- terra::cellFromXY(master_grid, coordinaten)

vertaal_df <- data.table(
  lokale_id = lokale_cellen,
  globale_id = studiegebied_globale_ids
)

template_TV <- id_raster_TV * NA
grens_web <- sf::st_as_sf(terra::project(area_shape, "EPSG:4326"))

rm(buffer_masker, lokale_cellen, coordinaten, studiegebied_globale_ids)
gc()
```

# Biotoopfiltering (BWK-codes)
```{r Biotoopfiltering}
df_nieuw <- read_csv(here("data/input/Excel_files/Resultaten_Totaal_Samengevoegd.csv"), show_col_types = FALSE)

resultaten_gegroepeerd <- df_nieuw %>%
  mutate(Soort_clean = tolower(trimws(Soort))) %>%
  filter(Soort_clean == soort) %>%
  group_by(Type) %>%
  nest(Data = c(Code, Match))

# DYNAMISCH INLEZEN VAN SCENARIO RDS I.P.V. DE REFERENTIETABEL
tabel_vlaanderen <- readRDS(scenario_path)
setDT(tabel_vlaanderen)
tabel_vlaanderen[, CODE := tolower(trimws(CODE))]

lijst_matches      <- list()
lijst_oppervlaktes <- list()

for(i in 1:nrow(resultaten_gegroepeerd)) {
  h_type <- resultaten_gegroepeerd$Type[i]
  h_data <- resultaten_gegroepeerd$Data[[i]]
  
  exact_codes <- tolower(trimws(h_data$Code[h_data$Match == "exact"]))
  bevat_codes <- tolower(trimws(h_data$Code[h_data$Match == "bevat"]))
  
  if(length(bevat_codes) > 0) {
    bevat_codes_escaped <- gsub("([\\.\\^\\$\\*\\+\\?\\(\\)\\[\\{\\\\\\|])", "\\\\\\1", bevat_codes)
    bevat_codes_anchored <- paste0("^", bevat_codes_escaped)
    regex_term <- paste0(bevat_codes_anchored, collapse = "|")
    tabel_gefilterd <- tabel_vlaanderen[CODE %in% exact_codes | grepl(regex_term, CODE)]
  } else {
    tabel_gefilterd <- tabel_vlaanderen[CODE %in% exact_codes]
  }
  
  tabel_TV <- tabel_gefilterd[cel_id %in% vertaal_df$globale_id]
  tabel_cel_som <- tabel_TV[, .(Oppervlakte = sum(BWK_FRAC, na.rm = TRUE)), by = .(cel_id)]
  
  r_match_type <- id_raster_TV * NA
  r_opp_type   <- id_raster_TV * NA
  
  if(nrow(tabel_cel_som) > 0) {
    tabel_cel_som[, Oppervlakte := pmin(Oppervlakte, 1)]
    tabel_cel_som[, Match := ifelse(Oppervlakte >= 0.01, 1, 0)]
    
    setnames(tabel_cel_som, "cel_id", "globale_id")
    tabel_finaal_mapping <- merge(tabel_cel_som, vertaal_df, by = "globale_id", all.x = TRUE)
    tabel_finaal_mapping <- tabel_finaal_mapping[!is.na(lokale_id)]
    
    if(nrow(tabel_finaal_mapping) > 0) {
      tabel_matches_clean <- tabel_finaal_mapping[Match == 1]
      if(nrow(tabel_matches_clean) > 0) {
        r_match_type[tabel_matches_clean$lokale_id] <- tabel_matches_clean$Match
      }
      r_opp_type[tabel_finaal_mapping$lokale_id] <- tabel_finaal_mapping$Oppervlakte
      
      lijst_matches[[h_type]]      <- r_match_type
      lijst_oppervlaktes[[h_type]] <- r_opp_type
    }
  }
}

voortplanting_bwk_max <- lijst_matches[["voortplanting_bwk1"]]
voortplanting_bwk_opp <- lijst_oppervlaktes[["voortplanting_bwk1"]]
not_vpt_max <- lijst_matches[["voortplanting_notbwk"]]
landbiotoop_bwk1_max <- lijst_matches[["landbiotoop_bwk1"]]
landbiotoop_bwk1_opp := lijst_oppervlaktes[["landbiotoop_bwk1"]]
landbiotoop_bwk_ruim_max <- lijst_matches[["landbiotoop_bwk_ruim"]]
landbiotoop_bwk_ruim_opp <- lijst_oppervlaktes[["landbiotoop_bwk_ruim"]]

rm(df_nieuw, resultaten_gegroepeerd, lijst_matches, lijst_oppervlaktes)
gc()
```

```{r waterlopen}
message("-> Huet-zones (waterlopen) inlezen en integreren...")
r_huetzon_vlaanderen <- rast(here("data/input/Raster_Vlaanderen/vlaanderen_huetzon_10m.tif"))
r_huetzon_local <- r_huetzon_vlaanderen %>% terra::crop(area_buffer_fix) %>% terra::resample(template_TV, method = "near")

valide_ids <- 3:10 
r_waterlopen_bin <- terra::ifel(r_huetzon_local %in% valide_ids, 1, NA)
r_waterlopen_opp <- terra::ifel(r_waterlopen_bin == 1, 0.01, NA)

rm(r_huetzon_vlaanderen, r_huetzon_local)

# Fusie & Maskering met ongeschikt habitat (not_vpt)
bruinekorenbout_voortplanting_bwk_max <- terra::cover(voortplanting_bwk_max, r_waterlopen_bin) %>% terra::mask(not_vpt_max, inverse = TRUE)
bruinekorenbout_voortplanting_bwk_opp <- terra::cover(voortplanting_bwk_opp, r_waterlopen_opp) %>% terra::mask(not_vpt_max, inverse = TRUE)

rm(voortplanting_bwk_max, voortplanting_bwk_opp, r_waterlopen_bin, r_waterlopen_opp, not_vpt_max)
gc()
```


```{r clustering}
message("-> Moving window buurtanalyses toepassen op voortplanting en landbiotoop 1...")

# Voortplanting filter (3x3 venster, drempel 0.04 ha)
r_buurt_count_a <- terra::focal(bruinekorenbout_voortplanting_bwk_max, w = 3, fun = "sum", na.rm = TRUE)
bruinekorenbout_voortplanting1_max <- terra::ifel(bruinekorenbout_voortplanting_bwk_max == 1 & r_buurt_count_a >= 4, 1, NA)

r_vpt_ha_per_cel <- (bruinekorenbout_voortplanting_bwk_opp > 0) * 0.01 * bruinekorenbout_voortplanting_bwk_opp
r_buurt_sum_ha_b <- terra::focal(r_vpt_ha_per_cel, w = 3, fun = "sum", na.rm = TRUE)
bruinekorenbout_voortplanting1_opp <- terra::ifel(!is.na(bruinekorenbout_voortplanting_bwk_opp) & r_buurt_sum_ha_b >= 0.04, bruinekorenbout_voortplanting_bwk_opp, NA)

# Landbiotoop 1 filter (5x5 venster, drempel 0.04 ha)
r_buurt_count_land_a <- terra::focal(landbiotoop_bwk1_max, w = 5, fun = "sum", na.rm = TRUE)
bruinekorenbout_landbiotoop1_max <- terra::ifel(landbiotoop_bwk1_max == 1 & r_buurt_count_land_a >= 4, 1, NA)

r_land_ha_per_cel <- (landbiotoop_bwk1_opp > 0) * 0.01 * landbiotoop_bwk1_opp
r_buurt_sum_land_b <- terra::focal(r_land_ha_per_cel, w = 5, fun = "sum", na.rm = TRUE)
bruinekorenbout_landbiotoop1_opp <- terra::ifel(!is.na(landbiotoop_bwk1_opp) & r_buurt_sum_land_b >= 0.04, landbiotoop_bwk1_opp, NA)

rm(r_buurt_count_a, r_vpt_ha_per_cel, r_buurt_sum_ha_b, r_buurt_count_land_a, r_land_ha_per_cel, r_buurt_sum_land_b, bruinekorenbout_voortplanting_bwk_max, bruinekorenbout_voortplanting_bwk_opp, landbiotoop_bwk1_max, landbiotoop_bwk1_opp)
gc()
```

```{r koppeling}
message("-> Symmetrische koppeling (25m) en robuuste bosnetwerkanalyse (10ha netto) uitvoeren...")

# Symmetrische koppeling water <=> land1
dist_water_max <- terra::distance(bruinekorenbout_voortplanting1_max)
land1_valide_max25m_bin <- terra::ifel(dist_water_max <= 25, 1, NA) %>% terra::mask(bruinekorenbout_landbiotoop1_max)
dist_land1_max <- terra::distance(land1_valide_max25m_bin)
water_valide_max25m_bin <- terra::ifel(dist_land1_max <= 25, 1, NA) %>% terra::mask(bruinekorenbout_voortplanting1_max)

dist_water_opp <- terra::distance(bruinekorenbout_voortplanting1_opp > 0)
land1_valide_max25m_opp <- terra::ifel(dist_water_opp <= 25, bruinekorenbout_landbiotoop1_opp, NA)
dist_land1_opp <- terra::distance(land1_valide_max25m_opp > 0)
water_valide_max25m_opp := terra::ifel(dist_land1_opp <= 25, bruinekorenbout_voortplanting1_opp, NA)

rm(dist_water_max, dist_land1_max, dist_water_opp, dist_land1_opp, bruinekorenbout_voortplanting1_max, bruinekorenbout_voortplanting1_opp, bruinekorenbout_landbiotoop1_max, bruinekorenbout_landbiotoop1_opp)

# Landbiotoop 2: Snelle 50m aggregatie en netto 10 ha filter
r_ruim_presence_opp <- !is.na(landbiotoop_bwk_ruim_opp) & landbiotoop_bwk_ruim_opp > 0
r_ruim_50m_opp <- terra::aggregate(r_ruim_presence_opp, fact = 5, fun = "max", na.rm = TRUE)
r_patches_50m_opp <- terra::patches(r_ruim_50m_opp, directions = 8, zeroAsNA = TRUE)
r_patches_10m_opp <- terra::disagg(r_patches_50m_opp, fact = 5) %>% terra::crop(landbiotoop_bwk_ruim_opp)

area_per_cel_ruim_opp <- r_ruim_presence_opp * 0.01 * landbiotoop_bwk_ruim_opp
df_area_ruim_opp <- terra::zonal(area_per_cel_ruim_opp, r_patches_10m_opp, fun = "sum", na.rm = TRUE)

if(nrow(df_area_ruim_opp) > 0) {
  ids_ruim_robuust_opp <- df_area_ruim_opp[df_area_ruim_opp[, 2] >= 10.0, 1]
} else { ids_ruim_robuust_opp <- c() }

if(length(ids_ruim_robuust_opp) > 0) {
  r_match_10m_opp <- terra::match(r_patches_10m_opp, ids_ruim_robuust_opp)
  landbiotoop2_valide_opp <- terra::mask(landbiotoop_bwk_ruim_opp, r_match_10m_opp)
} else { landbiotoop2_valide_opp <- id_raster_TV * NA }

# Afstandscheck 1km tot het robuuste bosnetwerk
if(!all(is.na(terra::values(landbiotoop2_valide_opp > 0, mat=FALSE)))) {
  dist_bos_opp1km <- terra::distance(landbiotoop2_valide_opp > 0)
  land1_gekoppeld_opp <- terra::ifel(dist_bos_opp1km <= 1000, land1_valide_max25m_opp, NA)
  water_gekoppeld_opp <- terra::ifel(dist_bos_opp1km <= 1000, water_valide_max25m_opp, NA)
  
  # Finale synthese
  ANB2019_BruineKorenbout2018_opp <- terra::cover(water_gekoppeld_opp, land1_gekoppeld_opp)
  final_opp <- terra::cover(ANB2019_BruineKorenbout2018_opp, landbiotoop2_valide_opp)
} else {
  final_opp <- template_TV * NA
}

rm(landbiotoop_bwk_ruim_max, landbiotoop_bwk_ruim_opp, r_ruim_presence_opp, r_ruim_50m_opp, r_patches_50m_opp, r_patches_10m_opp, area_per_cel_ruim_opp, df_area_ruim_opp, r_match_10m_opp, land1_valide_max25m_bin, water_valide_max25m_bin, land1_valide_max25m_opp, water_valide_max25m_opp, landbiotoop2_valide_opp)
if(exists("dist_bos_opp1km")) rm(dist_bos_opp1km, land1_gekoppeld_opp, water_gekoppeld_opp, ANB2019_BruineKorenbout2018_opp)
gc()
```

```{r export}
# 1. Map dynamisch genereren binnen de Rasters_Soorten hoofdmap
scenario_raster_dir <- here("data/output/Turnhouts_Vennegebied/Rasters_Soorten", scenario_naam)
if (!dir.exists(scenario_raster_dir)) dir.create(scenario_raster_dir, recursive = TRUE)

# 2. Omzetten naar binair (1/NA) conform de wasstraat-afspraak
if(!all(is.na(terra::values(final_opp, mat=FALSE)))) {
  werkelijk_scenario_rast <- terra::ifel(!is.na(final_opp) & final_opp > 0, 1, NA)
} else {
  werkelijk_scenario_rast <- terra::rast(template_TV, vals = NA)
}

bestandsnaam <- paste0("TV_", scenario_naam, "_", soort, ".tif")
file_path_scen <- file.path(scenario_raster_dir, bestandsnaam)

# 3. Kogelvrije opvulling (NA wordt 0 binnen de bufferzone)
export_rast <- terra::deepcopy(werkelijk_scenario_rast)
export_rast <- terra::mask(export_rast, area_buffer_fix)

if(all(is.na(terra::values(export_rast, mat=FALSE)))) {
  export_rast <- terra::ifel(is.na(export_rast), 0, 0)
  export_rast <- terra::mask(export_rast, area_buffer_fix, updatevalue = 0)
} else {
  export_rast <- terra::mask(export_rast, area_buffer_fix, updatevalue = 0)
}

writeRaster(export_rast, 
            filename = file_path_scen, 
            overwrite = TRUE, 
            gdal = c("COMPRESS=LZW"), 
            datatype = "INT1U")

message(paste("✓ Scenario-raster voor Bruine Korenbout succesvol weggeschreven naar:", file_path_scen))
```

```{r Interactieve kaart}
# 1. Lees de originele nulmeting/referentiekaart in vanuit de referentiemap
referentie_file <- here("data/output/Turnhouts_Vennegebied/Rasters_Soorten", "02_Werkelijke_Oppervlakte", paste0("Habitat_Werkelijke_Oppervlaktes_", soort, ".tif"))

if(file.exists(referentie_file)) {
  r_ref <- rast(referentie_file) %>% terra::resample(template_TV, method = "near")
} else {
  r_ref <- terra::rast(template_TV, vals = NA)
}

r_scen <- werkelijk_scenario_rast

# 2. RGB Matrix bepalen (1 = Rood/Verlies, 2 = Groen/Winst, 3 = Blauw/Status Quo)
r_rgb <- terra::ifel(!is.na(r_ref) & is.na(r_scen), 1, NA)                                     # Rood
r_rgb <- terra::cover(r_rgb, terra::ifel(is.na(r_ref) & !is.na(r_scen), 2, NA)) # Groen
r_rgb <- terra::cover(r_rgb, terra::ifel(!is.na(r_ref) & !is.na(r_scen), 3, NA)) # Blauw

r_rgb_web <- terra::project(terra::as.int(r_rgb), "EPSG:4326", method = "near")

# Kleurenpalet definiëren
kleuren_rgb <- c("#E74C3C", "#2ECC71", "#3498DB") 
pal_rgb <- colorFactor(palette = kleuren_rgb, levels = 1:3, na.color = "transparent")

leaflet() %>%
  addTiles(group = "OSM (Kaart)") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satelliet") %>%
  fitBounds(st_bbox(grens_web)[['xmin']], st_bbox(grens_web)[['ymin']], st_bbox(grens_web)[['xmax']], st_bbox(grens_web)[['ymax']]) %>%
  
  addRasterImage(r_rgb_web, colors = pal_rgb, opacity = 0.7, group = "Scenario Vergelijking") %>%
  addPolygons(data = grens_web, fill = FALSE, color = "black", weight = 3, group = "Grens TV") %>%
  
  addLegend(
    colors = kleuren_rgb,
    labels = c("Verloren gegaan habitat (Scenario)", "Nieuw bijgekomen habitat", "Status Quo (Behouden habitat)"),
    title = paste("Scenario vs Referentie:", scenario_naam),
    position = "bottomright"
  ) %>%
  addLayersControl(
    baseGroups = c("OSM (Kaart)", "Satelliet"),
    overlayGroups = c("Scenario Vergelijking", "Grens TV"),
    options = layersControlOptions(collapsed = FALSE)
  )
```